# Generated by Django 4.0.6 on 2022-07-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_menu_alter_userinfo_account_alter_userinfo_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=64, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='username',
            field=models.CharField(max_length=32, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='img',
            field=models.FileField(max_length=128, upload_to='Menu/', verbose_name='Logo'),
        ),
    ]
